In [5]:
df = ustcurve.nominal_rates('2026-08-01', '2026-09-22')
df

,date,1m,1.5m,2m,3m,4m,6m,1y,2y,3y,5y,7y,10y,20y,30y
0,2026-08-03,3.79,3.82,3.87,3.91,3.94,4.02,4.07,4.25,4.32,4.40,4.54,4.70,5.23,5.23
1,2026-08-04,3.78,3.80,3.85,3.89,3.91,4.00,4.04,4.20,4.25,4.33,4.47,4.63,5.18,5.18
2,2026-08-05,3.77,3.79,3.84,3.89,3.91,3.98,4.03,4.18,4.24,4.33,4.47,4.63,5.18,5.17
3,2026-08-06,3.80,3.80,3.84,3.90,3.92,3.99,4.06,4.25,4.31,4.40,4.53,4.69,5.22,5.22
4,2026-08-07,3.79,3.79,3.83,3.87,3.89,3.96,4.01,4.19,4.25,4.35,4.49,4.65,5.20,5.19
5,2026-08-10,3.79,3.80,3.84,3.89,3.91,4.00,4.04,4.25,4.31,4.41,4.56,4.72,5.25,5.25
6,2026-08-11,3.79,3.82,3.83,3.89,3.90,3.99,4.03,4.22,4.27,4.39,4.54,4.70,5.25,5.24
7,2026-08-12,3.78,3.79,3.80,3.87,3.89,3.97,4.00,4.20,4.25,4.38,4.52,4.68,5.24,5.24
8,2026-08-13,3.79,3.79,3.81,3.87,3.88,3.94,3.97,4.15,4.20,4.32,4.47,4.63,5.20,5.21
9,2026-08-14,3.79,3.80,3.81,3.86,3.88,3.95,3.98,4.17,4.24,4.36,4.51,4.68,5.25,5.25
10,2026-08-17,3.79,3.80,3.82,3.87,3.89,3.95,4.00,4.19,4.25,4.38,4.54,4.72,5.30,5.31
11,2026-08-18,3.78,3.78,3.82,3.86,3.88,3.94,3.99,4.19,4.26,4.37,4.53,4.71,5.28,5.28
12,2026-08-19,3.77,3.77,3.81,3.86,3.88,3.94,4.00,4.19,4.25,4.35,4.48,4.65,5.17,5.19
13,2026-08-20,3.80,3.77,3.79,3.87,3.88,3.94,3.99,4.19,4.26,4.39,4.53,4.69,5.20,5.23
14,2026-08-21,3.80,3.77,3.80,3.88,3.90,3.95,4.03,4.24,4.31,4.43,4.57,4.74,5.25,5.27
15,2026-08-24,3.79,3.78,3.80,3.87,3.90,3.96,4.04,4.24,4.31,4.41,4.55,4.70,5.21,5.23
16,2026-08-25,3.79,3.78,3.80,3.86,3.89,3.95,4.01,4.17,4.25,4.35,4.48,4.64,5.16,5.17
17,2026-08-26,3.80,3.78,3.80,3.85,3.88,3.94,4.02,4.19,4.29,4.37,4.51,4.66,5.17,5.18
18,2026-08-27,3.81,3.79,3.81,3.84,3.88,3.94,4.04,4.20,4.30,4.38,4.52,4.67,5.18,5.19
19,2026-08-28,3.84,3.83,3.86,3.90,3.94,4.02,4.15,4.34,4.41,4.48,4.59,4.73,5.21,5.22
20,2026-08-31,3.85,3.86,3.88,3.91,3.96,3.99,4.16,4.34,4.40,4.49,4.62,4.75,5.24,5.25
21,2026-09-01,3.85,3.88,3.89,3.92,3.97,4.00,4.18,4.39,4.46,4.55,4.66,4.79,5.27,5.27
22,2026-09-02,3.83,3.87,3.89,3.92,4.02,4.00,4.16,4.39,4.45,4.54,4.66,4.79,5.27,5.27
23,2026-09-03,3.83,3.82,3.91,3.89,3.99,3.95,4.11,4.34,4.41,4.52,4.63,4.77,5.25,5.25
24,2026-09-04,3.79,3.83,3.90,3.91,4.00,3.98,4.13,4.37,4.45,4.54,4.65,4.78,5.25,5.24
25,2026-09-08,3.81,3.88,3.91,3.94,4.02,4.00,4.15,4.39,4.44,4.57,4.68,4.80,5.26,5.25
26,2026-09-09,3.81,3.88,3.93,3.95,4.06,4.01,4.17,4.43,4.49,4.61,4.71,4.83,5.28,5.28
27,2026-09-10,3.91,3.93,4.01,4.00,4.11,4.07,4.28,4.56,4.63,4.75,4.84,4.95,5.39,5.37
28,2026-09-11,3.93,3.99,4.05,4.07,4.15,4.12,4.35,4.63,4.69,4.78,4.87,4.96,5.38,5.35
29,2026-09-14,3.94,4.00,4.06,4.11,4.18,4.18,4.37,4.65,4.73,4.80,4.88,4.97,5.37,5.34
30,2026-09-15,3.93,4.00,4.06,4.11,4.19,4.17,4.39,4.67,4.76,4.83,4.91,5.00,5.40,5.36
31,2026-09-16,3.96,4.00,4.07,4.14,4.24,4.22,4.45,4.74,4.82,4.86,4.94,5.01,5.39,5.35
32,2026-09-17,3.97,3.98,4.09,4.12,4.23,4.20,4.40,4.67,4.75,4.78,4.86,4.94,5.32,5.29
33,2026-09-18,3.97,3.98,4.10,4.14,4.24,4.24,4.44,4.76,4.83,4.86,4.93,5.01,5.38,5.34
34,2026-09-21,3.96,4.02,4.10,4.17,4.26,4.27,4.45,4.76,4.82,4.83,4.89,4.96,5.33,5.29
35,2026-09-22,3.97,4.04,4.09,4.16,4.26,4.26,4.43,4.71,4.81,4.83,4.89,4.96,5.33,5.29

In [2]:
import pandas as pd
import ustreasurycurve as ustcurve

df = ustcurve.nominal_rates('2026-08-01', '2026-09-22')[['date', '2y', '10y']]
df['date'] = pd.to_datetime(df['date'])

dates = pd.DataFrame({'date': pd.date_range('2026-09-01', '2026-09-22', freq='B')})

date2y10y = pd.merge_asof(
    dates,
    df.assign(source_date=df['date']).sort_values('date'),
    on='date',
    direction='backward'
)

print(date2y10y)

         date    2y   10y source_date
0  2026-09-01  4.39  4.79  2026-09-01
1  2026-09-02  4.39  4.79  2026-09-02
2  2026-09-03  4.34  4.77  2026-09-03
3  2026-09-04  4.37  4.78  2026-09-04
4  2026-09-07  4.37  4.78  2026-09-04
5  2026-09-08  4.39  4.80  2026-09-08
6  2026-09-09  4.43  4.83  2026-09-09
7  2026-09-10  4.56  4.95  2026-09-10
8  2026-09-11  4.63  4.96  2026-09-11
9  2026-09-14  4.65  4.97  2026-09-14
10 2026-09-15  4.67  5.00  2026-09-15
11 2026-09-16  4.74  5.01  2026-09-16
12 2026-09-17  4.67  4.94  2026-09-17
13 2026-09-18  4.76  5.01  2026-09-18
14 2026-09-21  4.76  4.96  2026-09-21
15 2026-09-22  4.71  4.96  2026-09-22

In [6]:
import pandas as pd
import ustreasurycurve as ustcurve

df = ustcurve.nominal_rates('2026-08-01', '2026-09-22')[['date', '2y', '10y']]
df['date'] = pd.to_datetime(df['date'])

dates = pd.DataFrame({
    'date': pd.date_range('2026-09-01', '2026-09-22', freq='B')
})

date2y10y = pd.merge_asof(
    dates,
    df.assign(source_date=df['date']).sort_values('date'),
    on='date',
    direction='backward'
)

date2y10y[['2y', '10y']] = date2y10y[['2y', '10y']].shift(1)

print(date2y10y)

         date    2y   10y source_date
0  2026-09-01   NaN   NaN  2026-09-01
1  2026-09-02  4.39  4.79  2026-09-02
2  2026-09-03  4.39  4.79  2026-09-03
3  2026-09-04  4.34  4.77  2026-09-04
4  2026-09-07  4.37  4.78  2026-09-04
5  2026-09-08  4.37  4.78  2026-09-08
6  2026-09-09  4.39  4.80  2026-09-09
7  2026-09-10  4.43  4.83  2026-09-10
8  2026-09-11  4.56  4.95  2026-09-11
9  2026-09-14  4.63  4.96  2026-09-14
10 2026-09-15  4.65  4.97  2026-09-15
11 2026-09-16  4.67  5.00  2026-09-16
12 2026-09-17  4.74  5.01  2026-09-17
13 2026-09-18  4.67  4.94  2026-09-18
14 2026-09-21  4.76  5.01  2026-09-21
15 2026-09-22  4.76  4.96  2026-09-22

In [7]:
import pandas as pd
import ustreasurycurve as ustcurve
from datetime import datetime
from zoneinfo import ZoneInfo

# Today's date in Czech time
today = datetime.now(ZoneInfo("Europe/Prague")).date()

# Last 30 days
start = pd.Timestamp(today) - pd.Timedelta(days=30)

# Get Treasury data
df = ustcurve.nominal_rates(
    start.strftime("%Y-%m-%d"),
    today.strftime("%Y-%m-%d")
)[['date', '2y', '10y']]

df['date'] = pd.to_datetime(df['date'])

# Business days for the last 30 days
dates = pd.DataFrame({
    'date': pd.date_range(start, today, freq='B')
})

# Match each business day to the latest available Treasury observation
date2y10y = pd.merge_asof(
    dates,
    df.assign(source_date=df['date']).sort_values('date'),
    on='date',
    direction='backward'
)

# One-observation lag
date2y10y[['2y', '10y']] = date2y10y[['2y', '10y']].shift(1)

# Show the result
date2y10y

         date    2y   10y source_date
0  2026-09-03   NaN   NaN  2026-09-03
1  2026-09-04  4.34  4.77  2026-09-04
2  2026-09-07  4.37  4.78  2026-09-04
3  2026-09-08  4.37  4.78  2026-09-08
4  2026-09-09  4.39  4.80  2026-09-09
5  2026-09-10  4.43  4.83  2026-09-10
6  2026-09-11  4.56  4.95  2026-09-11
7  2026-09-14  4.63  4.96  2026-09-14
8  2026-09-15  4.65  4.97  2026-09-15
9  2026-09-16  4.67  5.00  2026-09-16
10 2026-09-17  4.74  5.01  2026-09-17
11 2026-09-18  4.67  4.94  2026-09-18
12 2026-09-21  4.76  5.01  2026-09-21
13 2026-09-22  4.76  4.96  2026-09-22
14 2026-09-23  4.71  4.96  2026-09-23
15 2026-09-24  4.85  5.11  2026-09-24
16 2026-09-25  4.87  5.18  2026-09-25
17 2026-09-28  4.81  5.17  2026-09-28
18 2026-09-29  4.92  5.24  2026-09-29
19 2026-09-30  4.89  5.26  2026-09-30
20 2026-10-01  4.88  5.29  2026-10-01
21 2026-10-02  4.78  5.24  2026-10-02